### ISSUE TITLE
JsonApiGatewayCaller.kt tem muitas lateinit vars

### ISSUE THREAD

**Issue by alesaudate** [guijavax/api-escola#2]
Todas as lateinit vars que foram usadas nessa classe podem (e deveriam) ser substituidas por argumentos para o construtor (que tambem pode ser anotados com @Value sem problemas). 

O ideal seria ate refatorar esse argumento para o construtor usando uma classe separada, da forma como e descrita aqui: https://www.baeldung.com/configuration-properties-in-spring-boot

**Comment by guijavax** [comment]
Feito
